name: deploy packstack
on: [push, pull_request]

env:

  TESTS_TIMEOUT: 5 # in minutes

jobs:
  check:
    name: build and deploy packstack
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    
    - name: Build packstack container
      run: |

        cd ${GITHUB_WORKSPACE}/
        docker build -t packstack .

    - name: run packstack container
      run: |
        cd ${GITHUB_WORKSPACE}/
        sudo bash -c "source hack/utils.sh ; lv_create 4 "

        docker run --name packstack \
          --tty  --cap-add ALL \
          --privileged \
          --security-opt seccomp=unconfined \
           -v /dev/cinder-volumes:/dev/cinder-volumes \
           -v /dev/mapper:/dev/mapper \
           -v /lib/modules/:/lib/modules/ \
           --cgroup-parent=docker.slice \
          -v $(pwd):/src \
          -d packstack 

    - name: deploy packstack 
      run: |
        cd ${GITHUB_WORKSPACE}/
        docker exec -t packstack bash -x /deploy-packstack.sh

    - name: commit changes and list
      run: |
        docker commit packstack packstack-deployed
        docker images

    - name: push to quay
      run: |
        docker tag packstack-deployed quay.io/eslutsky/packstack:latest
        echo ${{ secrets.QUAY_PASSWORD }} | docker login -u ${{ secrets.QUAY_USERNAME }} --password-stdin quay.io
        docker push quay.io/eslutsky/packstack:latest